version: '3.8'

services:
  face-encoding-api:
    image: veriffdocker/face-encoding-test-task:latest
    ports:
      - "8000:8000"
    networks:
      - app-network

  face-encoding-service:
    build: .
    ports:
      - "8001:8001"
    depends_on:
      - face-encoding-api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
